### PR TITLE
Include instructions to upload git history in architecture FAQ

### PR DESCRIPTION
**Pull request by janlaan**

### CODE REVIEW

**Comment by janlaan** [comment]
@dennis-sig

**Comment by dennis-sig** [comment]
@janlaan I find the description a bit confusing. It implies you need to actively do something to get the Git history into Sigrid, which is not true for like 95% of people using Sigrid CI. I would suggest to change the list:

1. If you're using Sigrid CI using the examples provided in this documentation, your Git history is automatically anonymized and published to Sigrid.
2. If you are *not* using Sigrid CI.
  - (your points)

**Review by dennis-sig — CHANGES_REQUESTED** [review]
See my suggestion, that will help to avoid confusion.

**Comment by dennis-sig** [comment]
Ended up being turned into @MichielCuijpers 's proposal.

**Pull request closed without merging**
